#!/usr/bin/env bash

HTTP_PORT=80

post() {
    shopt -s extquote

    export LC_ALL=C
    unset headers_read

    host=${1%%/*}
    path=${1#*/}

    [[ $path == $host ]] && path=""

	if exec 3<>/dev/tcp/${host}/${HTTP_PORT}; then
    	printf "POST /${path} HTTP/1.1\r\nHost: ${host}\r\nUser-Agent: bURL/Bash ${BASH_VERSION}\r\n\r\n" >&3
    	IFS=
    	while read -r -t 1 line 0<&3; do        	
			if [ "${line:0:12}" == "HTTP/1.1 200" ]; then
				break
			else
				echo "post: $host:$HTTP_PORT/${path} ${line:0:12}" 1>&2
				echo "`date "+%d/%m/%Y %X"` $host:$HTTP_PORT/${path} ${line:0:12}" 1>> post.err
				exit 1
			fi		
    	done
    	exec 3<&-
    else
    	exec 3<&-
    	echo "`date "+%d/%m/%Y %X"` unable to connect: $host:$HTTP_PORT/${path}" 1>&2
    	echo "`date "+%d/%m/%Y %X"` unable to connect: $host:$HTTP_PORT/${path}" 1>>post.err
    	exit 1
    fi
}

usage() {
    cat <<EOF
Usage: $0 [options] URL
Options:
  -h            display usage help
  -p <port>     use alternative port number (default: 80)
EOF
}

if [[ $# -eq 0 ]]; then
    usage
    exit 1
fi

while getopts 'hip:' option; do
    case "$option" in
        h)
            usage
            exit 0
            ;;

        p)
            HTTP_PORT=$OPTARG
            ;;

        *)
            usage
            exit 1
            ;;
    esac
done
shift $(( $OPTIND - 1))

post ${1/http:\/\/}

